const departamentos = [
  {
    id: "PE-AMA",
    nombre: "amazonas",
    nombre_original: "Amazonas",
    longitud: "-77.85",
    latitud: "-6.22",
  },
  {
    id: "PE-ANC",
    nombre: "ancash",
    nombre_original: "Áncash",
    longitud: "-77.93",
    latitud: "-9.56",
  },
  {
    id: "PE-APU",
    nombre: "apurimac",
    nombre_original: "Apurímac",
    longitud: "-72.94",
    latitud: "-14.05",
  },
  {
    id: "PE-ARE",
    nombre: "arequipa",
    nombre_original: "Arequipa",
    longitud: "-71.54",
    latitud: "-16.40",
  },
  {
    id: "PE-AYA",
    nombre: "ayacucho",
    nombre_original: "Ayacucho",
    longitud: "-74.22",
    latitud: "-13.16",
  },
  {
    id: "PE-CAJ",
    nombre: "cajamarca",
    nombre_original: "Cajamarca",
    longitud: "-78.50",
    latitud: "-7.16",
  },
  {
    id: "PE-CAL",
    nombre: "callao",
    nombre_original: "Callao",
    longitud: "-77.12",
    latitud: "-12.06",
  },
  {
    id: "PE-CUS",
    nombre: "cusco",
    nombre_original: "Cusco",
    longitud: "-71.97",
    latitud: "-13.52",
  },
  {
    id: "PE-HUV",
    nombre: "huancavelica",
    nombre_original: "Huancavelica",
    longitud: "-74.97",
    latitud: "-12.78",
  },
  {
    id: "PE-HUC",
    nombre: "huanuco",
    nombre_original: "Huánuco",
    longitud: "-76.24",
    latitud: "-9.93",
  },
  {
    id: "PE-ICA",
    nombre: "ica",
    nombre_original: "Ica",
    longitud: "-75.729",
    latitud: "-14.07",
  },
  {
    id: "PE-JUN",
    nombre: "junin",
    nombre_original: "Junín",
    longitud: "-74.79",
    latitud: "-11.56",
  },
  {
    id: "PE-LAL",
    nombre: "la libertad",
    nombre_original: "La Libertad",
    longitud: "-78.28",
    latitud: "-7.97",
  },
  {
    id: "PE-LAM",
    nombre: "lambayeque",
    nombre_original: "Lambayeque",
    longitud: "-79.91",
    latitud: "-6.70",
  },
  {
    id: "PE-LMA",
    nombre: "lima",
    nombre_original: "Lima Metropolitana",
    longitud: "-76.95",
    latitud: "-11.9",
  },
  {
    id: "PE-LIM",
    nombre: "lima region",
    nombre_original: "Lima Región",
    longitud: "-76.64",
    latitud: "-11.92",
  },
  {
    id: "PE-LOR",
    nombre: "loreto",
    nombre_original: "Loreto",
    longitud: "-74.63",
    latitud: "-4.28",
  },
  {
    id: "PE-MDD",
    nombre: "madre de dios",
    nombre_original: "Madre de Dios",
    longitud: "-70.53",
    latitud: "-12.05",
  },
  {
    id: "PE-MOQ",
    nombre: "moquegua",
    nombre_original: "Moquegua",
    longitud: "-70.94",
    latitud: "-17.20",
  },
  {
    id: "PE-PAS",
    nombre: "pasco",
    nombre_original: "Pasco",
    longitud: "-75.53",
    latitud: "-10.48",
  },
  {
    id: "PE-PIU",
    nombre: "piura",
    nombre_original: "Piura",
    longitud: "-80.63",
    latitud: "-5.20",
  },
  {
    id: "PE-PUN",
    nombre: "puno",
    nombre_original: "Puno",
    longitud: "-70.04",
    latitud: "-15.84",
  },
  {
    id: "PE-SAM",
    nombre: "san martin",
    nombre_original: "San Martín",
    longitud: "-76.73",
    latitud: "-7.23",
  },
  {
    id: "PE-TAC",
    nombre: "tacna",
    nombre_original: "Tacna",
    longitud: "-70.25",
    latitud: "-18.01",
  },
  {
    id: "PE-TUM",
    nombre: "tumbes",
    nombre_original: "Tumbes",
    longitud: "-80.54",
    latitud: "-3.85",
  },
  {
    id: "PE-UCA",
    nombre: "ucayali",
    nombre_original: "Ucayalí",
    longitud: "-73.40",
    latitud: "-9.93",
  },
];

module.exports = departamentos;
