name: actualizar_datos

on:
  workflow_dispatch:
  #schedule:
    # Se ejecutrar todos los dias a las 6:00 PM hora peruana
    #- cron: 00 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Obtener Fecha
        run: echo "NOW=$(date +'%d/%m/%Y - %H:%M:%S UTC 00')" >> $GITHUB_ENV
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm i
      - run: npm run actualizar
      - run: git config user.name 'Brian Aguilar D'
      - run: git config user.email 'aguilar.16999@gmail.com'
      - run: git add .
      - run: git commit -m "Fecha actualizada $NOW"
      - run: git push
